name: Scheduled or Manual Trigger

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      original_trigger:
        required: false
        type: string
        description: 'get the trigger type from the caller workflow'

jobs:
  call-main:
    permissions:
      contents: write
    uses: ./.github/workflows/fetch-game-data.yml
    secrets: inherit
    with:
      original_trigger: ${{ inputs.original_trigger || github.event_name}}
